### ISSUE TITLE
Issue running with kitchen.bat

### ISSUE THREAD

**Issue by TESAARON** [cdeptula/tdeoutputplugin#14]
Hello, 

I am getting the following error when I run a TDE extract job from kitchen.bat

![image](https://user-images.githubusercontent.com/10795276/38422194-bdc0bd9a-39a1-11e8-9e27-ab546ba2bafa.png)

I followed the steps in the Readme and the job works perfectly from Spoon.bat. 

Any ideas what could be causing this? 

Many thanks,
Aaron

**Comment by cdeptula** [comment]
I cannot replicate this.  I do not believe this has anything to do with the TDE plugin itself.  My best guess, but it is truly a guess, is that you edited the kitchen.bat or spoon.bat files somehow and accidentally deleted or mistyped something.

The best I can recommend is try re-installing Pentaho and re-installing the plugin again to make sure you did not accidentally delete or typo something.
