### ISSUE TITLE
logs location

### ISSUE THREAD

**Issue by llealgt** [cdeptula/tdeoutputplugin#17]
More than a bug, this is a question, but i didn't know where to ask it, where can i look for logs for the plugin? (in linux).

My need comes because i have a simple pentaho job that parses an csv file and creates a tableau extract, but it's failing when running it in the server (linux) and working fine when running it in developer machine(mac). Other jobs run fine in the server so i know it's not related to API installation.

**Comment by cdeptula** [comment]
Any logs would be in the standard Pentaho logs.  This plugin does not write any custom logs.  You should look at the Pentaho Server logs to determine why the transformation is failing.

**Comment by llealgt** [comment]
Thanks for your help but obviously the reason why i asked for additional logs is because the standard pentaho logs didn't provide any useful information beyond "error configuring extract"
