### ISSUE TITLE
 Exception trying to close file: java.lang.NullPointerException

### ISSUE THREAD

**Issue by churtado** [cdeptula/tdeoutputplugin#6]
Hello,

I'm getting the same error reported in issue 5 (closed). But I will try to give you all the necessary information. 

I'm running Ubuntu 14.04, using Open JDK, version 1.7.0_65. I've built PDI from source and downloaded the plugin from the marketplace. I downloaded the data extract API from Tableau's web site here:
http://www.tableausoftware.com/products/api-download?ref=lp&signin=8729add136a1f2a3ca23f588fa584906&1[os]=linux

(downloaded the linux version). Set the LD_LIBRARY_PATH variable to point to <HOME>/TDE-API-Linux-64Bit/lib64/dataextract, where I extracted the api. I hope this is correct.

I started the server in the bin folder (./tdeserver64) and ran a transformation, and got the errors you'll see at the end of the post. I get the feeling it has to do with permissions, but I'm not too sure.

If necessary I can provide a sample transformation. I just take some string data from an excel file (about a dozen string columns) and try to export it to tableau.

Is there anything I'm doing wrong? 

Log statements:

2014/11/10 10:51:21 - output to file.0 - ERROR (version TRUNK-SNAPSHOT, build 1 from 2014-10-07 18.06.25 by carlos) : Exception trying to close file: java.lang.NullPointerException
2014/11/10 10:51:21 - output to file.0 - ERROR (version TRUNK-SNAPSHOT, build 1 from 2014-10-07 18.06.25 by carlos) : 
2014/11/10 10:51:21 - output to file.0 - Error opening extract : com.tableausoftware.TableauException: server did not call us back
2014/11/10 10:51:21 - output to file.0 - ERROR (version TRUNK-SNAPSHOT, build 1 from 2014-10-07 18.06.25 by carlos) : Error initializing step [output to file]
2014/11/10 10:51:21 - contacts ETL - ERROR (version TRUNK-SNAPSHOT, build 1 from 2014-10-07 18.06.25 by carlos) : Step [output to file.0] failed to initialize!
2014/11/10 10:51:21 - output to file.0 - ERROR (version TRUNK-SNAPSHOT, build 1 from 2014-10-07 18.06.25 by carlos) : Exception trying to close file: java.lang.NullPointerException
2014/11/10 10:51:21 - Spoon - ERROR (version TRUNK-SNAPSHOT, build 1 from 2014-10-07 18.06.25 by carlos) : contacts ETL: preparing transformation execution failed
2014/11/10 10:51:21 - Spoon - ERROR (version TRUNK-SNAPSHOT, build 1 from 2014-10-07 18.06.25 by carlos) : org.pentaho.di.core.exception.KettleException: 
2014/11/10 10:51:21 - Spoon - We failed to initialize at least one step.  Execution can not begin!
2014/11/10 10:51:21 - Spoon - 
2014/11/10 10:51:21 - Spoon - 
2014/11/10 10:51:21 - Spoon - 	at org.pentaho.di.trans.Trans.prepareExecution(Trans.java:1149)
2014/11/10 10:51:21 - Spoon - 	at org.pentaho.di.ui.spoon.trans.TransGraph$27.run(TransGraph.java:3989)
2014/11/10 10:51:21 - Spoon - 	at java.lang.Thread.run(Thread.java:744)
2014/11/10 10:51:21 - contacts ETL - ERROR (version TRUNK-SNAPSHOT, build 1 from 2014-10-07 18.06.25 by carlos) : Errors detected!
2014/11/10 10:51:21 - contacts ETL - ERROR (version TRUNK-SNAPSHOT, build 1 from 2014-10-07 18.06.25 by carlos) : Errors detected!

**Comment by cdeptula** [comment]
Fixed in release 1.1.0
