### ISSUE TITLE
Tableau 9

### ISSUE THREAD

**Issue by churtado** [cdeptula/tdeoutputplugin#8]
Apologies if this is not the place to ask this. I was wondering if you have plans to upgrade this plugin for version 9?

**Comment by cdeptula** [comment]
I honestly have not looked at Tableau 9 to determine if any updates to this plugin will be required.  If I have time and updates are required I probably will update this plugin for Tableau 9 at some point.

I of course am always happy to accept pull requests with any necessary updates if you need this faster than I get to it.

**Comment by cdeptula** [comment]
I have downloaded and reviewed the latest version of the Tableau data extract API and do not see any changes that would be required to support Tableau 9.  From my limited testing this plugin appears to support Tableau version 9.
