### ISSUE TITLE
Tableau API change

### ISSUE THREAD

**Issue by henryjarend** [cdeptula/tdeoutputplugin#9]
I've followed the directions and worked to resolve this issue however I believe that the Tableau API calls might have changed names. It appears that the error is similar to one on the [common errors] (https://github.com/cdeptula/tdeoutputplugin/wiki/Common-Errors) however following the resolution steps on that page did not help to resolve any of the errors. Does this plugin support PDI 5.3 and Tableau 8.3 and 9.0?

**Comment by cdeptula** [comment]
I just tested using the latest version of the Tableau API using PDI 5.3 and this plugin was successfully able to write a TDE file.  The error is most likely a missed step or a typo in the additional installation instructions found in the README.  https://github.com/cdeptula/tdeoutputplugin/blob/master/README.md

If you have verified you followed the installation instructions correctly and you are still experiencing issues please re-open with the full stack trace of the error you are experiencing.
